### ISSUE TITLE
OpenAIRealtimeBetaLLMService function calling not working in 0.0.53

### ISSUE THREAD

**Issue by markbackman** [pipecat-ai/pipecat#1063]
# Description
This is a bug. As a result of implementing #970, function calling for `OpenAIRealtimeBetaLLMService` is no longer working.

### Environment
- pipecat-ai version: 0.0.53
- python version: Any
- OS: Any

### Issue description
When the `OpenAIRealtimeBetaLLMService` attempts to use a function, it results in the following error:
```
2025-01-22 08:38:03.728 | ERROR    | pipecat.services.openai_realtime_beta.context:_push_aggregation:223 - Error processing frame: 'FunctionCallResultFrame' object has no attribute 'run_llm'
```

### Repro steps
Run example `19-openai-realtime-beta.py`

### Expected behavior
Function call works

### Actual behavior
Function call results in an error (see description)

**Comment by markbackman** [comment]
Fixing this issue in #1065.
