### ISSUE TITLE
Regression in v0.0.102: Daily SDK SFU signaling timeout with Gemini Live native audio

### ISSUE THREAD

**Issue by sbenodiz** [pipecat-ai/pipecat#3743]
### pipecat version

0.0.102    

### Python version

3.11 

### Operating System

Linux (Docker python:3.11-slim on Railway)        

## Summary

  Upgrading from `pipecat-ai==0.0.101` to `pipecat-ai==0.0.102` causes Daily SDK's native layer to emit `CallManagerEventSfuSigPresence took
  longer than 2s` errors, breaking voice audio entirely. Pinning back to 0.0.101 resolves the issue.

  ## Environment Details

  - **daily-python**: 0.23.0
  - **LLM**: `GeminiLiveLLMService` with native audio (`gemini-2.5-flash-native-audio-preview`)
  - **VAD**: `SileroVADAnalyzer` with `stop_secs=0.8`, `min_volume=0.3`
  - **Transport**: `DailyTransport` with `transcription_enabled=True`

  ## Pipeline

  ```python
  Pipeline([
      transport.input(),
      rtvi,
      context_aggregator.user(),  # SileroVADAnalyzer
      user_transcript_capture,     # Custom FrameProcessor
      llm,                         # GeminiLiveLLMService
      transcript_processor,        # Custom FrameProcessor
      output_transport,
      context_aggregator.assistant(),
  ])

  Error

  {
    "level": "ERROR",
    "fields": {
      "message": "Task 'CallManagerEventSfuSigPresence' took longer than 2s"
    },
    "target": "daily_common_utils::sync::native_types"
  }

  Audio is completely broken when this error appears — no sound in either direction.

  Steps to Reproduce

  1. Deploy with pipecat-ai==0.0.102 and GeminiLiveLLMService + DailyTransport
  2. Connect a client to the Daily room
  3. SFU signaling timeout errors appear, audio does not work

  Downgrading to pipecat-ai==0.0.101 (identical code, same daily-python 0.23.0) resolves the issue immediately.

  Investigation

  We isolated this through systematic A/B testing:
  - Same code, same daily-python==0.23.0, same google-genai version
  - Only variable: pipecat-ai 0.0.101 vs 0.0.102
  - 0.0.101 works every time, 0.0.102 fails every time

  Suspected Cause

  Looking at the v0.0.102 changelog, the most likely candidate is the change of default user turn stop strategy to
  TurnAnalyzerUserTurnStopStrategy. This may add enough per-frame processing overhead to block the asyncio event loop, causing Daily's native
  Rust layer to timeout on SFU signaling tasks.

  Workaround

  Pin to pipecat-ai==0.0.101 in requirements.txt.
  ```

### Reproduction steps

 1. Install pipecat-ai==0.0.102 with daily-python==0.23.0                                                                                       
  2. Create a pipeline using GeminiLiveLLMService (native audio model) + DailyTransport + SileroVADAnalyzer                                      
  3. Connect a client to the Daily room                                                                                                          
  4. Observe: SFU signaling timeout errors appear, audio does not work in either direction                                                       
  5. Downgrade to pipecat-ai==0.0.101 (same code, same daily-python) — audio works immediately        

### Expected behavior

 Audio should work the same as in v0.0.101. The Daily SDK's native SFU signaling tasks should complete within their 2s timeout, and
  bidirectional audio should function normally.

### Actual behavior

Daily SDK's native Rust layer emits repeated errors:

  {"level":"ERROR","fields":{"message":"Task 'CallManagerEventSfuSigPresence' took longer than
  2s"},"target":"daily_common_utils::sync::native_types"}

  Followed by WebSocket errors:
  {"message":"failed to send message on websocket: Protocol(SendAfterClosing)"}

  Audio is completely broken — no sound in either direction. The issue is 100% reproducible with 0.0.102 and never occurs with 0.0.101.

  We isolated this through systematic A/B testing:
  - Same application code, same daily-python==0.23.0, same google-genai version
  - Only variable changed: pipecat-ai 0.0.101 vs 0.0.102
  - 0.0.101 works every time, 0.0.102 fails every time

  Suspected cause: the v0.0.102 change of default user turn stop strategy to TurnAnalyzerUserTurnStopStrategy may add enough per-frame processing
   to block the asyncio event loop, causing Daily's native layer to timeout.

  Workaround: pin pipecat-ai==0.0.101

### Logs

```shell

```

**Comment by markbackman** [comment]
I'll need help from @aconchillo to look into this one.

I see you're doing something custom that I want to make sure I understand:
You're using Daily's built-in transcription even though the Gemini Live model outputs a user transcript. I'm assuming this is intentional and you're doing it to increase the transcript accuracy. Is that right? Does the `user_transcript_capture` processor just block the TranscriptionFrames pushed upstream? (Make sure you're not blocking other frames too.)

A few other simplifications that you could provide (not related to the issue you're seeing):
1. To handle the assistant transcripts, you can just listen to the `on_assistant_turn_stopped` event to get the assistant transcript. You can see this pattern in the example. (You can also do the same for the user transcript, either from Gemini or Daily.)
2. RTVI is not integrated into the Pipeline. You can pass in a custom RTVI to the PipelineTask if needed. Docs: https://docs.pipecat.ai/server/frameworks/rtvi/introduction.

**Comment by markbackman** [comment]
Hmm, just a hunch, it seems like you could be running out of CPU. A quick option to try would be to replace the `TurnAnalyzerUserTurnStopStrategy` with the `SpeechTimeoutUserTurnStopStrategy`:

```python
from pipecat.turns.user_stop.speech_timeout_user_turn_stop_strategy import (
    SpeechTimeoutUserTurnStopStrategy,
)

user_aggregator, assistant_aggregator = LLMContextAggregatorPair(
    context,
    user_params=LLMUserAggregatorParams(
        user_turn_stop_strategy=SpeechTimeoutUserTurnStopStrategy(user_speech_timeout=0.6),
        vad_analyzer=SileroVADAnalyzer(),
    ),
)
```

Where you set the user_speech_timeout for how long you want the user to have to speak.

Alternatively, monitor the CPU to see if it's being consumed.

**Comment by sbenodiz** [comment]
Thanks for the feedback! We simplified our pipeline based on your suggestions:                                                                 
                                                                                                                                                 
  Changes made:                                                                                                                                  
  1. Disabled Daily transcription — now using only Gemini's input_audio_transcription (no more dual transcription)                               
  2. Removed RTVI from Pipeline — kept as observer only via RTVIObserver(rtvi) on PipelineTask
  3. Removed custom UserTranscriptCapture processor — replaced with on_user_turn_stopped event handler on the user aggregator
  4. Simplified pipeline to: transport.input() → user_aggregator → llm → transcript_processor → transport.output() → assistant_aggregator

  The only custom processor remaining is a lightweight TranscriptProcessor that handles bot speaking state
  (BotStartedSpeaking/BotStoppedSpeaking), live streaming text (TTSTextFrame), and sending messages to the client via Daily data channel.

  Note: Our app requires real-time transcripts for both user and bot — we display them in the client UI as the conversation happens (live
  streaming for the bot, completed turns for both). That's why we still need input_audio_transcription=True and a processor to capture
  TTSTextFrame. This may be relevant since the official example doesn't use transcription.

  This works correctly on 0.0.101.

  Regarding the SpeechTimeoutUserTurnStopStrategy suggestion — we tried it but user_turn_stop_strategy is not a valid parameter on
  LLMUserAggregatorParams in 0.0.102:

  LLMUserAggregatorParams.__init__() got an unexpected keyword argument 'user_turn_stop_strategy'

  We haven't yet tested 0.0.102 with just the simplified pipeline (without the strategy override). Should we try that, or is there a different
  way to pass user_turn_stop_strategy in 0.0.102?

**Comment by markbackman** [comment]
You could simplify even further. RTVI is responsible for client/server messaging and events. So, you can handle the bot-output event, for example, to receive the bot's transcripts in real-time. I think for Gemini Live, this may be paced with the actual audio output. Check it out:
https://docs.pipecat.ai/client/js/api-reference/callbacks#param-on-bot-output

This would let you remove the custom FrameProcessor from the pipeline.

As for the code snippet, my apologies. I shared the wrong object structure. This is correct (I verified it this time!):
```
from pipecat.turns.user_stop import SpeechTimeoutUserTurnStopStrategy
from pipecat.turns.user_turn_strategies import UserTurnStrategies

    user_aggregator, assistant_aggregator = LLMContextAggregatorPair(
        context,
        user_params=LLMUserAggregatorParams(
            user_turn_strategies=UserTurnStrategies(
                stop=[
                    SpeechTimeoutUserTurnStopStrategy(user_speech_timeout=0.5),
                ],
            ),
            vad_analyzer=SileroVADAnalyzer(params=VADParams(stop_secs=0.5)),
        ),
    )
```

I would try this change because CPU might be what's impacting you.

**Comment by sbenodiz** [comment]
Thank you so much @markbackman! Both suggestions were helpful. Here's what we implemented:

**1. SpeechTimeoutUserTurnStopStrategy — working on 0.0.102 ✅**

Upgraded to 0.0.102 with the correct syntax you provided. This works perfectly:

```python
from pipecat.turns.user_stop import SpeechTimeoutUserTurnStopStrategy
from pipecat.turns.user_turn_strategies import UserTurnStrategies

context_aggregator = LLMContextAggregatorPair(
    context,
    user_params=LLMUserAggregatorParams(
        user_turn_strategies=UserTurnStrategies(
            stop=[
                SpeechTimeoutUserTurnStopStrategy(user_speech_timeout=0.5),
            ],
        ),
        vad_analyzer=SileroVADAnalyzer(params=VADParams(stop_secs=0.8)),
    ),
)
```

We kept `stop_secs=0.8` (vs your 0.5) since our users are children who tend to pause while formulating their thoughts.

**2. RTVI `on-bot-output` for transcripts — not applicable to our setup**

Our iOS/Android/web clients don't use the RTVI client library — they receive messages via Daily's raw data channel (`callClient:appMessageAsJson` on iOS, etc.) with our own message protocol (`transcript`, `transcript_complete`, `speaking_started`, `speaking_ended`, `user_speaking`, `session_terminated`). So we can't rely on RTVI's `on-bot-output` callback without reworking all three clients. The custom `TranscriptProcessor` stays for now.

**3. RTVI setup note — needs both pipeline + observer**

While implementing this, we hit an issue worth documenting: RTVIProcessor needs to be both **in the pipeline** (to receive `StartFrame`) and **in observers** (via `RTVIObserver`). Having it as observer-only causes `"Trying to process OutputTransportMessageUrgentFrame but StartFrame not received yet"` errors on every frame. Having it in pipeline-only causes pipecat to warn `"RTVIProcessor found in pipeline but no RTVIObserver in observers"`. The correct setup:

```python
rtvi = RTVIProcessor()

pipeline = Pipeline([
    transport.input(),
    user_aggregator,
    llm,
    transcript_processor,
    rtvi,                    # IN the pipeline
    output_transport,
    context_aggregator.assistant(),
])

task = PipelineTask(
    pipeline,
    observers=[RTVIObserver(rtvi)],  # AND in observers
)
```

**4. Memory leak fix — subprocess isolation**

Separately, we addressed the native memory leak from [our other issue](https://github.com/pipecat-ai/pipecat/issues/3753) by running each bot session in its own subprocess via `asyncio.create_subprocess_exec`. Parent process RSS now stays flat across sessions (~129MB → 129.5MB after 5 calls, vs +27MB growth over 14 sessions before). This works around the native memory leaks in daily-python/grpcio/onnxruntime until they're fixed upstream.

Everything is working well on 0.0.102 now. Thanks for the help!

**Comment by markbackman** [comment]
2. Got it. The Pipecat client SDKs are built on top of Daily's client SDKs, so if you ever make the switch, it may make life easier for you. Not a requirement though.
3. Correct. The RTVIObserver receives the RTVIProcessor instance. Both are built into the Pipeline by default now.
4. We'll take a look at that other issue and can work through it there.

Glad this helped. I'll close this one out for now.

**Comment by tomresqhealth** [comment]
I too am trying to use Pipecat v0.0.102 with Gemini Live API, with some additional tool calling as well (for the agent to display videos on demand.) My agent worked well in v0.0.101, but upgrading to 102 today broke it badly.

Gemini Pro 3 (fast) and I went around and around this afternoon, and Gemini is convinced that I cannot use v0.0.102 to achieve my use case. I asked it to output a summary of the issue we're experiencing, pasted here in case it helps inform this issue:

**GEMINI'S ANALYSIS**

To provide the Pipecat team with a clear technical report of the regression you've encountered, you can use the following summary. It uses the logs and evidence from your session to highlight the event-loop blockage specifically affecting Gemini Live native audio agents.

**Issue Report: v0.0.102 Regression - Event Loop Blockage with Gemini Live & DailyTransport**

**Description**
After upgrading from v0.0.101 to v0.0.102, agents utilizing GeminiLiveLLMService with DailyTransport experience a complete failure in audio processing and signaling. The Python asyncio event loop becomes unresponsive, leading to SFU signaling timeouts and a failure of the bot to process or emit audio frames.

**Evidence: SFU Signaling Timeouts**
The following error appears consistently in the logs shortly after the bot joins the session:
{"timestamp":"...","level":"ERROR","fields":{"message":"Task 'CallManagerEventSfuSigPresence' took longer than 2s"},"target":"daily_common_utils::sync::native_types"}

**Evidence: Pipeline Linkage Warnings**
The framework's new auto-injection logic conflicts with manual RTVIProcessor configurations required for custom lifecycle handlers:
WARNING | pipecat.pipeline.task:__init__:342 - PipelineTask#0: RTVIProcessor and RTVIObserver found, skipping default ones. They are both added by default, no need to add them yourself.

**Technical Analysis**
Event Loop Starvation: The regression appears linked to the new default user turn-stop strategy (TurnAnalyzerUserTurnStopStrategy) introduced in v0.0.102. The per-frame processing overhead of the local turn-detection model, when combined with high-bandwidth native audio streaming from Gemini Live, starves the asyncio loop.

Daily SDK Impact: Because the loop is blocked, the Daily native layer cannot complete its signaling heartbeats within the 2-second threshold, causing the SFU connection to freeze.

Linkage Failure: When a manual RTVIProcessor is used (necessary for on_client_ready handlers), the runner fails to correctly link the CancelFrame path if the RTVIObserver isn't also manually registered, resulting in a terminal hang on SIGINT (Ctrl+C).

**Observed Behavior**
v0.0.101: 100% stable; low TTFB; clean shutdown.

v0.0.102: 100% reproducible failure; audio breaks in both directions; terminal hangs on shutdown.

**Requested Action**
Review the overhead of the LocalSmartTurnAnalyzerV3 on the asyncio event loop during high-priority native audio streaming tasks to prevent SFU signaling timeouts in future releases (v0.0.103).

Recommended Workaround used: Pinning to pipecat-ai[daily,google,silero]==0.0.101.
