### ISSUE TITLE
ParallelPipelineSink error: '__process_queue' attribute missing after recent FrameProcessor changes

### ISSUE THREAD

**Issue by jamsea** [pipecat-ai/pipecat#2385]
## Bug Description

After the recent changes to how FrameProcessor handles system frames (commit a5ea6e16), running examples that use `ParallelPipeline` results in an `AttributeError`.

## Error Message

```
ParallelPipelineSink#0::__input_frame_task_handler: unexpected exception: 'ParallelPipelineSink' object has no attribute '_FrameProcessor__process_queue'
```

## Root Cause

The issue stems from a race condition introduced in commit a5ea6e16 "FrameProcessor: system frames are now queued". 

In the new implementation:
1. `__input_frame_task_handler` tries to access `self.__process_queue` (line 786 in frame_processor.py)
2. However, `__process_queue` is only created when `__create_process_task()` is called
3. `__create_process_task()` is only called when a `StartFrame` is received (in the `__start` method)
4. But the input task is created immediately in `setup()` and can receive frames before `StartFrame` is processed

This causes the `__input_frame_task_handler` to try to access a non-existent `__process_queue` attribute.

## Steps to Reproduce

1. Set up environment with Python 3.12 and recent pipecat version
2. Run any example that uses `ParallelPipeline`, such as:
   ```bash
   uv run examples/foundational/15-switch-voices.py
   ```
3. The error occurs when `ParallelPipelineSink` processes frames before receiving a `StartFrame`

## Environment

- **Python Version**: 3.12.9
- **Pipecat Commit**: ad1841b739152da00dfa502f34799eaa09df6c96
- **Operating System**: macOS
- **Affected File**: `src/pipecat/processors/frame_processor.py`
- **Problem Introduced**: Commit a5ea6e16 (Aug 4, 2025)

## Affected Code

In `src/pipecat/processors/frame_processor.py`, line 786:
```python
async def __input_frame_task_handler(self):
    while True:
        (frame, direction, callback) = await self.__input_queue.get()

        if isinstance(frame, SystemFrame):
            await self.__process_frame(frame, direction, callback)
        else:
            await self.__process_queue.put((frame, direction, callback))  # ← This line fails
```

The `__process_queue` is only created in `__create_process_task()` which is called in `__start()` when a `StartFrame` is received.

## Proposed Fix

The `__process_queue` should be created when the input task is created, not just when `StartFrame` is received. This ensures that non-system frames can be queued even before the processor is formally "started".

Possible fix in `__create_input_task()`:
```python
def __create_input_task(self):
    """Create the frame input processing task."""
    if not self.__input_frame_task:
        self.__input_queue = FrameProcessorQueue(self.task_manager)
        # Ensure process queue exists for non-system frames
        if not hasattr(self, '_FrameProcessor__process_queue'):
            self.__create_process_task()
        self.__input_frame_task = self.create_task(self.__input_frame_task_handler())
```

## Impact

This affects any pipeline using `ParallelPipeline`, which is commonly used in examples for features like:
- Voice switching (as in `15-switch-voices.py`)
- Multiple TTS services
- Parallel processing branches

The issue prevents these examples from running and may affect production pipelines using parallel processing.

**Comment by markbackman** [comment]
Note: this is on an unreleased version, ~`0.0.78.dev`.

**Comment by filipi87** [comment]
And it is already fixed now. 🚀
